# database generated on 2026-07-22 18:45 GMT
!!omap
- /home/lnx-141209/Desktop/FluxCore/verification/riscof/riscv-arch-test/riscv-test-suite/rv32i_m/Zifencei/src/Fencei.S:
    commit_id: 274b6cd787d4d5b0b6c41424b9b7dcca495a9d4b
    isa:
    - RV32I_Zifencei
    parts: !!omap
    - '1':
        check:
        - check ISA:=regex(.*32.*)
        - check ISA:=regex(.*I.*)
        - check ISA:=regex(.*Zifencei.*)
        define:
        - def TEST_CASE_1=True
        coverage_labels:
        - fencei
