#!/usr/bin/env python3
"""Golden-vector generator for the FluxCore RV32F FPU (Phase E compliance sweep).

Emits round-to-nearest-even reference results for FMUL/FADD/FSUB/FMADD/FDIV/FSQRT
as a compiled-in SystemVerilog include (fp_sweep_vectors.svh) of packed arrays.
The reference is the host IEEE-754 double datapath: float32 operands are computed
in double precision and rounded once back to float32 (correctly-rounded for
+,-,*,/ and sqrt); FMA uses math.fma for a true single rounding. Special values
(0, inf, subnormals, boundaries) are mixed with a large random sample so the
sweep exercises the mantissa/rounding paths far beyond the directed tests.

Compiling the vectors in (rather than $readmemh) keeps the sweep independent of
the simulator's runtime working directory.

Usage:  python3 verification/scripts/fp_vectors.py [N] [out.svh]
"""
import math
import random
import struct
import sys
from pathlib import Path


def f32(x: float) -> float:
    """Round a Python float to the nearest float32 value."""
    return struct.unpack("<f", struct.pack("<f", x))[0]


def bits(x: float) -> int:
    return struct.unpack("<I", struct.pack("<f", f32(x)))[0]


def from_bits(b: int) -> float:
    return struct.unpack("<f", struct.pack("<I", b & 0xFFFFFFFF))[0]


# A pool of interesting float32 bit patterns.
SPECIAL = [
    0x00000000, 0x80000000,               # +/-0
    0x3F800000, 0xBF800000,               # +/-1
    0x40000000, 0x40490FDB,               # 2.0, pi
    0x7F7FFFFF, 0xFF7FFFFF,               # +/-MAX
    0x00800000, 0x80800000,               # +/-min normal
    0x00000001, 0x80000001,               # +/-min subnormal
    0x007FFFFF, 0x00400000,               # subnormals
    0x7F800000, 0xFF800000,               # +/-inf
    0x3F000000, 0x3FC00000, 0x40200000,   # 0.5, 1.5, 2.5
]


def rand_bits(rng: random.Random) -> int:
    if rng.random() < 0.25:
        return rng.choice(SPECIAL)
    # random exponent biased toward the normal range to keep FMA spans small
    return rng.getrandbits(32)


def is_nan(b: int) -> bool:
    return (b & 0x7F800000) == 0x7F800000 and (b & 0x007FFFFF) != 0


def sv_array(name: str, vals: list[int]) -> str:
    body = ", ".join(f"32'h{v:08x}" for v in vals)
    return f"    localparam logic [31:0] {name} [0:{len(vals)-1}] = '{{{body}}};\n"


def gen(n: int, out: Path) -> None:
    rng = random.Random(0xF10A7)
    out.parent.mkdir(parents=True, exist_ok=True)

    def make(fn, nargs, fma=False):
        cols = [[] for _ in range(nargs)]
        res = []
        made = 0
        while made < n:
            if fma:
                fa = [f32(rng.uniform(-1024.0, 1024.0)) for _ in range(3)]
                ab = [bits(x) for x in fa]
            else:
                ab = [rand_bits(rng) for _ in range(nargs)]
                fa = [from_bits(x) for x in ab]
            try:
                r = math.fma(*fa) if fma else fn(*fa)
            except (ValueError, ZeroDivisionError, OverflowError):
                continue
            rb = bits(f32(r))
            if is_nan(rb) or any(is_nan(x) for x in ab):
                continue   # NaN payloads are covered by the directed tests
            for i in range(nargs):
                cols[i].append(ab[i])
            res.append(rb)
            made += 1
        return cols, res

    ops = [
        ("MUL",  lambda a, b: f32(f32(a) * f32(b)), 2, False),
        ("ADD",  lambda a, b: f32(f32(a) + f32(b)), 2, False),
        ("SUB",  lambda a, b: f32(f32(a) - f32(b)), 2, False),
        ("DIV",  lambda a, b: f32(f32(a) / f32(b)), 2, False),
        ("SQRT", lambda a: f32(math.sqrt(f32(a))) if f32(a) >= 0 else float("nan"), 1, False),
        ("FMA",  None, 3, True),
    ]

    lines = [
        "// AUTO-GENERATED by verification/scripts/fp_vectors.py — do not edit.\n",
        "// RV32F golden vectors (round-to-nearest-even) for the compliance sweep.\n",
        f"    localparam int SWEEP_N = {n};\n",
    ]
    for name, fn, nargs, fma in ops:
        cols, res = make(fn, nargs, fma)
        labels = ["A", "B", "C"][:nargs]
        for lbl, col in zip(labels, cols):
            lines.append(sv_array(f"{name}_{lbl}", col))
        lines.append(sv_array(f"{name}_R", res))
        print(f"generated {n} {name} vectors")

    out.write_text("".join(lines))
    print(f"wrote {out}")


if __name__ == "__main__":
    n = int(sys.argv[1]) if len(sys.argv) > 1 else 256
    out = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(
        "verification/unit/execution/fp_sweep_vectors.svh")
    gen(n, out)
