rtl/common/fluxcore_pkg.sv
rtl/common/rv32_isa_pkg.sv
rtl/common/pipeline_pkg.sv
rtl/common/imm_gen.sv
rtl/common/regfile.sv
rtl/decode/decoder.sv
rtl/execution/alu.sv
rtl/execution/branch_unit.sv
rtl/pipeline/if_id_reg.sv
rtl/pipeline/id_ex_reg.sv
rtl/pipeline/ex_mem_reg.sv
rtl/pipeline/mem_wb_reg.sv
rtl/frontend/fetch_unit.sv
rtl/execution/mul_div_unit.sv
rtl/execution/execute_stage.sv
rtl/memory/mem_stage.sv
rtl/core/wb_stage.sv
rtl/core/forwarding_unit.sv
rtl/core/pipeline_ctrl.sv
rtl/core/csr_unit.sv
rtl/core/fluxcore_top.sv
verification/integration/tb_branch.sv
