// verification/unit/execution/tb_fp_sweep.sv
//
// Randomized compliance sweep for the FluxCore RV32F arithmetic units. Compiles
// in a large table of golden round-to-nearest-even vectors generated by
// verification/scripts/fp_vectors.py from the host IEEE-754 datapath, and checks
// fp_mul / fp_addsub / fp_fma / fp_divsqrt bit-for-bit against them. Flags are
// not checked here (the host reference does not model them precisely); the
// directed unit tests cover flags and NaN payloads. This sweep is about volume
// coverage of the mantissa/rounding paths across the whole float32 space.

`timescale 1ns / 1ps
`default_nettype none

import fluxcore_pkg::*;
import rv32_isa_pkg::*;

module tb_fp_sweep;

    `include "fp_sweep_vectors.svh"

    // ---- combinational DUTs ----
    word_t   ca, cb, cc;
    fpu_op_e cop;
    word_t   mul_r, add_r, sub_r, fma_r;
    fflags_t mul_f, add_f, sub_f, fma_f;

    fp_mul    u_mul (.a_i(ca), .b_i(cb), .rm_i(FRM_RNE), .result_o(mul_r), .fflags_o(mul_f));
    fp_addsub u_add (.a_i(ca), .b_i(cb), .op_i(FPU_ADD), .rm_i(FRM_RNE), .result_o(add_r), .fflags_o(add_f));
    fp_addsub u_sub (.a_i(ca), .b_i(cb), .op_i(FPU_SUB), .rm_i(FRM_RNE), .result_o(sub_r), .fflags_o(sub_f));
    fp_fma    u_fma (.a_i(ca), .b_i(cb), .c_i(cc), .op_i(FPU_MADD), .rm_i(FRM_RNE), .result_o(fma_r), .fflags_o(fma_f));

    // ---- sequential DUT (div/sqrt) ----
    logic clk = 0, rst = 1;
    always #5 clk = ~clk;
    word_t   da, db;
    fpu_op_e dop;
    logic    dstart;
    word_t   dres;
    fflags_t dflags;
    logic    dbusy, didle;
    fp_divsqrt u_ds (.clk(clk), .rst(rst), .a_i(da), .b_i(db), .op_i(dop), .rm_i(FRM_RNE),
                     .start_i(dstart), .result_o(dres), .fflags_o(dflags),
                     .busy_o(dbusy), .idle_o(didle));

    int errors = 0;

    task automatic ck(input string op, input int i, input word_t got, input word_t exp);
        if (got !== exp) begin
            errors++;
            if (errors < 20)
                $display("FAIL %s[%0d]: got=%08h exp=%08h", op, i, got, exp);
        end
    endtask

    task automatic run_ds(input fpu_op_e op, input word_t a, input word_t b,
                          input word_t exp, input string lbl, input int i);
        @(negedge clk); da=a; db=b; dop=op; dstart=1'b1;
        @(negedge clk); dstart=1'b0;
        while (dbusy) @(negedge clk);
        #1; ck(lbl, i, dres, exp);
    endtask

    integer k;
    initial begin : body
        dstart = 0; da='0; db='0; dop=FPU_DIV;
        repeat (3) @(posedge clk); @(negedge clk); rst = 0;

        // combinational sweeps
        for (k = 0; k < SWEEP_N; k++) begin
            ca = MUL_A[k]; cb = MUL_B[k]; #1; ck("MUL", k, mul_r, MUL_R[k]);
            ca = ADD_A[k]; cb = ADD_B[k]; #1; ck("ADD", k, add_r, ADD_R[k]);
            ca = SUB_A[k]; cb = SUB_B[k]; #1; ck("SUB", k, sub_r, SUB_R[k]);
            ca = FMA_A[k]; cb = FMA_B[k]; cc = FMA_C[k]; #1; ck("FMA", k, fma_r, FMA_R[k]);
        end

        // sequential sweeps (div / sqrt)
        for (k = 0; k < SWEEP_N; k++) begin
            run_ds(FPU_DIV,  DIV_A[k],  DIV_B[k], DIV_R[k],  "DIV",  k);
            run_ds(FPU_SQRT, SQRT_A[k], 32'h0,    SQRT_R[k], "SQRT", k);
        end

        if (errors == 0)
            $display("[FP-SWEEP] PASS: %0d vectors/op verified (mul/add/sub/fma/div/sqrt).", SWEEP_N);
        else
            $fatal(1, "[FP-SWEEP] FAIL: %0d mismatches", errors);
        $finish;
    end : body

endmodule : tb_fp_sweep

`default_nettype wire
